all : al

al : 
	gcc -o avmc alphaVirtualMachine.c avm_stack.c avm_table.c  constTables.c dispatser.c execute_arithmetic_operations.c execute_assign_functions.c execute_calling_functions.c execute_equality_operations.c execute_tables_functions.c libraryFunctions.c -lm
